### ISSUE TITLE
在overfolw工作异常

### ISSUE THREAD

**Issue by Fish-LP** [MrXiaoM/CommandYouWant#4]
似乎无法获取任何消息

**Comment by MrXiaoM** [comment]
不接受任何模糊的反馈，“似乎”在我这里就是没问题

**Comment by Fish-LP** [comment]
> # 触发命令所需权限
> # (留空为不注册权限 若不注册权限将无法限定该命令可在何处使用)
> # 权限注册后无法注销 如要修改，重启生效
> perm: mcmotd.mcp.strictmcl
> 
> # 权限描述
> perm-desc: /mcp 别名
> 
> # 权限不足提示，留空不提示
> deny-tips: 权限不足
> 
> # 触发命令的关键词规则
> keyword: '服务器'
> 
> # 触发命令的关键词规则别名列表。请保持参数数量与主规则一致并 避免与其他命令的规则冲突
> keywords-list: []
> 
> # 各个关键词的屏蔽规则
> keyword-block: {}
> 
> # 触发屏蔽规则提示，留空不提示
> keyword-block-tips: 被省流了
> 
> # 执行命令
> actions:
>   - 'cmd:/mcp'
>   - 'send:get data...'
> 
> # 在执行命令时，是否检查权限，若不检查将忽略权限强制执行
> is-action-check-perm: false
> 
> 
> 
> # 执行命令所需金钱的货币类型
> # 留空为不花费金钱
> # 该功能需要安装 mirai-economy-core 插件生效
> cost-money-currency: 'mirai-coin'
> # 执行命令所需金钱
> cost-money: 1
> # 是否从全局上下文扣除金钱
> # 若关闭该项，将在用户执行命令所在群的上下文扣除金钱
> # 私聊执行命令将强制使用全局上下文
> cost-money-global: false
> # 执行命令金钱不足提醒
> # $at 为 @ 发送者，$quote 为回复发送者，$cost 为需要花费的金 钱
> cost-money-not-enough: '$quote你没有足够的 Mirai 币 ($cost)  来执行该命令!'

如此设置的情况下，有根权限，在私聊或者群聊发送"服务器"一定有回复吧
_使用luckperms，没有安装经济插件
安装了commandchat_
在终端我只看到了消息事件

**Comment by MrXiaoM** [comment]
暂不支持无参数命令，下个版本更新
